server:
  port: ${PORT:8083}
spring:  
  jpa:
    show-sql : true
    generate-ddl : false
    properties:
      hibernate:
        show_sql: true 
        use_sql_comments: true
        format_sql: true
        type_sql: true
        ddl-auto: update
# JWT
security:
  jwt:
    expiresInHours: 1
    secret: $10$6GBcDoRjwQcHvZpdGtEXIuNO/e4CMgWochkaQwa4RzvvztlJl0Pcq
eureka:
  client:
    enabled: true 
---
#################################### AMBIENTE ######################################################
spring:
  application:
    name: auth-service-dev
  profiles: dev
  datasource:
    url: jdbc:postgresql://ec2-34-195-115-225.compute-1.amazonaws.com:5432/d3v46croeli6c3?sslmode=require&user=aiomltflvwkzjh&password=67199a164ae12c6f9a7cff724ef7f65aa3c1212277462a7e5d2ab9df9efe432b&loadBalanceHosts=true
    password: 67199a164ae12c6f9a7cff724ef7f65aa3c1212277462a7e5d2ab9df9efe432b
    username: aiomltflvwkzjh
    platform: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
        maximum-pool-size: 8
        connectionTimeout: 30000
        idleTimeout: 10000
        maxLifetime: 10000
    tomcat:
      max-idle: 10
      max-active: 10
      max-wait: 10000
      default-auto-commit: true
  jpa:
    database: POSTGRESQL
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
 
eureka:
  instance:
    port: ${PORT:9090}
    hostname: ${DOMAIN_NAME}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URL}
  server:
    wait-time-in-ms-when-sync-empty: 3000
--- 
################################### TESTE #####################################################
spring:
  application:
    name: auth-service-test
  profiles: test
  database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    username: lucasdsf
    platform: h2
    password: 12345678
    url: jdbc:h2:~/h2bd2;AUTO_SERVER=TRUE
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
eureka:
  instance:
    port: ${PORT:9090}
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000
